(function() {
  var TIMER, after, step, suspend, test;

  TIMER = this;

  suspend = require('coffeenode-suspend');

  step = suspend.step;

  after = suspend.after;

  test = function() {
    return step(function*(resume) {
      var idx, timer, _i, _results;
      TIMER.new_timer();
      TIMER.new_timer('helo world');
      timer = TIMER.new_timer('simple random timeout');
      _results = [];
      for (idx = _i = 0; _i <= 8; idx = ++_i) {
        _results.push((function(idx) {
          TIMER.start(timer, idx);
          return after(2 + (2 - Math.random() * 4), function() {
            return TIMER.stop(timer, idx);
          });
        })(idx));
      }
      return _results;
    });
  };

  test();

}).call(this);
/****generated by https://github.com/loveencounterflow/larq****/